spring:
  servlet:
    multipart:
      max-file-size: 0MB
      max-request-size: 1MB
      enabled: true
      file-size-threshold: 0
      location: D:\\temp
      resolve-lazily: false
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      database: mysql
      show-sql: ture

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/hanzy?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  redis:
    #Redis库编号
    database: 0
    #redis实例地址
    host: 127.0.0.1
    #redis端口
    port: 6379
    #redis密码
    password: 123456
    jedis:
      pool:
        #连接池最大连接数
        max-active: 8
        #最大空闲连接数
        max-idle: 8
        #最大阻塞等待时间
        max-wait: -1ms
        #最小空闲连接数
        min-idle: 0
  freemarker:
    #HttpServletRequest的属性是否可以覆盖controller中的model同名项
    allow-request-override: false
    #HttpSession的属性是否可以覆盖controller中model的同名项
    allow-session-override: false
    #是否开启缓存
    cache: false
    #模板文件编码
    charset: utf-8
    #是否检查模板位置
    check-template-location: true
    #Contrnt-Type的值
    content-type: text/html
    #是否将HttpServletRequest中的属性添加到Model中
    expose-request-attributes: false
    #是否将HTTPSession中的属性添加到Model中
    expose-session-attributes: false
    #模板文件名后缀
    suffix: .ftl
    #模板文件位置
    template-loader-path: classpath:/templates/